### ISSUE TITLE
Setup Shibboleth SP and request/configure attributes

### ISSUE THREAD

**Issue by eporter23** [emory-libraries/dlp-selfdeposit#221] opened 2024-04-11 18:33 UTC
This ticket follows prior tickets to review and request available attributes and setup an EC2 (oe24-shibb) for running Shibboleth.

In a prior ticket #128, we anticipate that it may be easier to do the SP setup first, and then start to work through the attributes we have identified as needed. 

See also Service Now KB01317

**Comment by eporter23** [comment] 2024-04-18 18:22
We have a base installation on the EC2, but it needs to be configured.

**Comment by kbowaterskelly** [comment] 2024-05-01 01:52
Installed, configured, in testing.

Are we going to run the SP over Apache or via a Ruby gem or etc?

**Comment by tmill29** [comment] 2024-05-02 18:25
DNS and firewall request will be submitted today

**Comment by kbowaterskelly** [comment] 2024-05-03 04:25
This is taking longer than expected to submit the requests due to my relative unfamiliarity with performing these processes for AWS instances - I am still working on it.

**Comment by kbowaterskelly** [comment] 2024-05-03 04:46
REQ176831 - Requested firewall opening for Emory's internal networks - not public to internet
INC04259923 - Map A record to AWS elastic ip - shib.open.library.emory.edu

**Comment by kbowaterskelly** [comment] 2024-05-04 02:31
I'm going to need to consult with Beth or etc. on the firewall/VPC situation because I'm not familiar with it enough to get this firewall ticket completed. Moving to blocked to review on Monday.

**Comment by jcrompton42** [comment] 2024-05-09 17:19
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-security-groups.html
https://docs.aws.amazon.com/vpc/latest/userguide/working-with-security-groups.html

**Comment by jcrompton42** [comment] 2024-05-17 14:19
I have configured a security group in aws so that when connected to the VPN, 10.65.89.218/secure is reachable and redirects to login.emory.edu, where it results in an error. I don't know if this is expected or not at this point. If @kbowaterskelly is not back by monday I can investigate further.

**Comment by kbowaterskelly** [comment] 2024-05-23 02:23
Question for tomorrow: This EC2 instance has an Amazon Linux version with an EOL of 2025-06-30. Do we want to pause work on this Shib deployment until we can reimage it? Do we want to do a test deployment of Shib with the test IdP and then reimage it? etc. etc.  @jcrompton42 should weigh in here.

**Comment by kbowaterskelly** [comment] 2024-05-23 02:25
Other EC2 instances may be impacted by this issue. We should check on that.

**Comment by jcrompton42** [comment] 2024-05-23 14:34
I don't think an ec2 instance expiring next year should halt work going on now.

**Comment by eporter23** [comment] 2024-05-28 17:10
Submitting request to Gerry today.

**Comment by kbowaterskelly** [comment] 2024-05-28 23:36
Having an issue with a mis-created DNS record so need to work on this tomorrow after it's corrected

**Comment by kbowaterskelly** [comment] 2024-05-30 02:37
After discussion with @rotated8 today, I was able to get "dummy authentication" setup so that we can get this going. Our SP at "shib.open.library.emory.edu" is fully configured and functional and metadata is available here: https://shib.open.library.emory.edu/Shibboleth.sso/Metadata
 
Once Rosalyn has signed the confidentiality agreement and Gerry has done his work, it should be ready to go.  We agreed that the next step is to begin configuring the application side of things to make the requests to Shibboleth, though at this time it is not a blocker since I was able to "secure" some dummy documents hosted on the server. We should be ready to begin to scope and plan that work with the coming sprint.

**Comment by kbowaterskelly** [comment] 2024-05-30 02:40
Here is a list of all of the "default attributes" that were available on the form.

Attribute Name	Definition                   
givenName	First Name
emoryGivenName	Directory First Middle Name
sn	Surname or last name
cn	Common Name (directory name)
title	Job title
ou	Organizational Unit (department)
telephoneNumber	Telephone number
facsimileTelephoneNumber	Fax number
mail 	e-mail address
businessCategory	School or Division
uid	NetID
serialNumber	Emory public person ID (PPID)
organizationalStatus	Type: Faculty, Staff, Student, Staff/Student, Retired, Sponsored, Administrative
suppressInfo	Y means the person is Info Suppressed, and the existence of this person must not be revealed.
isMemberOf	Semicolon- delimited list of University LDAP groups that contain NetID. 


I requested all of these except for "suppressinfo" which I wasn't sure about, but we can discuss it before I finalize the request. I believe there are metadata attributes we are aware of (and are available) besides these "defaults" so if there is something missing from that list, no sweat, as long as it is/was on the attribute map xml, we can still request those and that is independent of these confidentiality forms. I'm going to move this to Review for discussion.

**Comment by kbowaterskelly** [comment] 2024-05-30 19:11
INC04276520 submitted for to authorize the sp

**Comment by bwatson78** [comment] 2024-06-04 20:18
PR made: https://github.com/emory-libraries/dlp-selfdeposit/pull/323
This gets us to the ability to reach Auth via `/users/saml/sign_in`.

**Comment by kbowaterskelly** [comment] 2024-06-05 00:30
They requested additional information and possibly signatures when I followed up. I'll get that back to them tomorrow or by Thursday at the latest.

**Comment by kbowaterskelly** [comment] 2024-06-07 02:05
Submitted updated form, requested all available attributes from attribute map.

**Comment by kbowaterskelly** [comment] 2024-06-13 17:01
The document has been revised and resubmitted, along with an email to Anne Marie since they do not seem to be receiving my updates to the ticket itself. A copy is attached for reference.[OIT Emory Login Request Form (1).pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnBoQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8acc8954f317e53b542e92edcc9cbf64621353e/OIT%20Emory%20Login%20Request%20Form%20%281%29.pdf)

**Comment by kbowaterskelly** [comment] 2024-06-18 02:53
After discussion with Anne Marie and Collin Brittle, it seems we will be able to get all the attributes we requested in the previous ticket. 

We will be required to use the "libraryUserGroup" attribute to determine entitlement to access library resources per their requirements - I can put the list of possible values wherever it is convenient or appropriate. This will take care of some of their data stewardship concerns. It sounds like we will just need to hear back from them at this point and then we can talk to Gerry about implementation.

**Comment by kbowaterskelly** [comment] 2024-06-20 17:03
Anne Marie Alexander
Public notes (emailed to the user)•2d ago
Attributes sent to HR and student data stewards:
uid – NetID
serialNumber – Public Person ID
displayName – preferred first name + surname
orgStatus – person type
title – employee title
ou – department
academiccareer – school
mail – preferred email address
isMemberOf - libraryUserGroup

**Comment by kbowaterskelly** [comment] 2024-06-20 17:13
libraryUserGroup
// ALL POSSIBLE VALUES THAT CAN BE RELEASED
             // Deceased
             // Administrative
             // Staff
             // Faculty
             // EU Job Eligible
             // Student Applicant
             // Sponsored
             // Retired
             // Unknown
             // Pre-start
             // Undergraduate/Staff
             // Graduate/Staff
             // Staff/Undergraduate
             // Staff/Graduate
             // Undergraduate
             // Graduate
             // Healthcare

**Comment by bwatson78** [comment] 2024-06-24 15:57
I just checked the log-in ability of Test and Arch by visiting `/users/saml/sign_in` on each. I get to this endpoint: https://shib.open.library.emory.edu/. The page shows the following: <img width="958" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXVJQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d0dc376cd8b232d53f15b6190672babe51f00311/Screenshot_20240624_105322.png" alt="Screenshot_20240624_105322.png" />
I'd love to know if this means we can progress with them--have them redirect to us. If it does, the endpoint they need to direct to is: POST to `/users/saml/auth`

**Comment by kbowaterskelly** [comment] 2024-06-24 21:29
able to browse to shib.open.library.emory.edu and log in and see content

**Comment by bwatson78** [comment] 2024-06-25 15:23
I have confirmed that I cannot just pass in the redirect URL into our settings. Shibboleth doesn't pickup on it.

**Comment by kbowaterskelly** [comment] 2024-06-26 17:54
Here's an example of session output which looks like it might be missing some things.

Miscellaneous
Session Expiration (barring inactivity): 479 minute(s)
Client Address: 10.110.111.129
SSO Protocol: urn:oasis:names:tc:SAML:2.0:protocol
Identity Provider: https://login.emory.edu/idp/shibboleth
Authentication Time: 2024-06-26T17:52:36.282Z
Authentication Context Class: urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
Authentication Context Decl: (none)

Attributes
displayName: 1 value(s)
mail: 1 value(s)
ou: 1 value(s)
title: 1 value(s)
uid: 1 value(s)

**Closed** 2024-06-27 18:13 UTC
Labels: Middleware
